### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by apol-katsunori-kaai** [MKLab-ITI/visil#19]
Hi!
I ran the code below on google colab.
`!python calculate_similarity.py --query_file queries.txt --database_file database.txt --load_queries --workers 2`
Then I get an error like this:(There is also a [similar issue,](https://github.com/MKLab-ITI/visil/issues/16) I checked if there is a file in the directory, and it is actually there.)
```
/content/visil_pytorch
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0% 0/80 [00:00<?, ?it/s]> Extract features of the query videos
  6% 5/80 [00:34<08:31,  6.82s/it, query_id=CWTpqQYDqzk]
Traceback (most recent call last):
  File "calculate_similarity.py", line 48, in <module>
    for video in pbar:
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/visil_pytorch/datasets/generators.py", line 23, in __getitem__
    video = utils.load_video(self.videos[index][1], fps=self.fps, cc_size=self.cc_size, rs_size=self.rs_size)
  File "/content/visil_pytorch/utils.py", line 48, in load_video
    frames = center_crop(frames, cc_size)
  File "/content/visil_pytorch/utils.py", line 13, in center_crop
    top = int(np.maximum(0, (old_size[0] - desired_size)/2))
IndexError: tuple index out of range
```

**Comment by apol-katsunori-kaai** [comment]
It was just that the specified video file did not exist.
